print('My name is Mark Darling')
print('August 23, 2017')
print('C:\Python36')
print('On my personal laptop')
print('Yes, I can run Python from any folder on my computer now.')
exit=input('Strike any key to Exit:')
